### PR TITLE
Removes unnecessary, legacy build code for inclusion of axe dependencies.

### LINKED ISSUE #248: Axe-core double inclusion via Webpack
Host apps are including `axe-core` duplicate times, once via the standard `app.import` method set up by the addon, and the second time via Webpack, which is presumably from `ember-auto-import`. Both appear in the test-support.js bundle. There is also associated log output when building the host app:

```
WARNING in ./node_modules/axe-core/axe.js 11:149698-149705
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ /private/var/folders/c5/w1hrxnv55sx_303npp2r5q_h000510/T/broccoli-29237IvTtzxKWMRSR/cache-2222-bundler/staging/tests.js
 @ multi /private/var/folders/c5/w1hrxnv55sx_303npp2r5q_h000510/T/broccoli-29237IvTtzxKWMRSR/cache-2222-bundler/staging/l.js /private/var/folders/c5/w1hrxnv55sx_303npp2r5q_h000510/T/broccoli-29237IvTtzxKWMRSR/cache-2222-bundler/staging/tests.js

WARNING in ./node_modules/axe-core/axe.js
Module not found: Error: Can't resolve 'crypto' in '/Users/andlee/workspace/lighthouse-web_trunk/node_modules/axe-core'
 @ ./node_modules/axe-core/axe.js
```

Standard Inclusion
Screen Shot 2021-04-06 at 12 51 15 PM

Webpack Injection
Screen Shot 2021-04-06 at 12 51 30 PM

Not sure if it's unique to a certain set of dependencies, but the host app includes:
- ember-cli 3.16.2
- ember-source 3.16.9
- ember-auto-import 1.11.2

### PR DESCRIPTION
**Pull request by MelSumner**
should fix #248

- checked with @ef4 & the lines removed are per his recommendation (as the author of `ember-auto-import`) - seems we were doing some redundant things that `ember-auto-import` was already providing. 
- updates the version of `ember-qunit`

I did notice that some of the dummy app tests are failing. Perhaps we should plan to revisit the app and update it. I'll make a new issue for that.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -25,7 +23,7 @@ module.exports = {
 
     const hasMagicallyProvidedQUnit = versionChecker
       .for('ember-qunit')
-      .lt('5.0.0-beta.1');
+      .lt('5.1.4');
```
Comment (rwjblue) [inline index.js:26]: I think this part of the change should be reverted, see my comment on #249 for details

Comment (MelSumner) [reply index.js]: fixed! 👍

**Review by scalvert — APPROVED** [review]
I'm unsure myself as to whether this is 100% required or not, but I'll defer to @ef4 to determine the correct path here.

**Review by ef4 — APPROVED** [review]
This looks good to me. But there are some things left behind that are no longer used after this PR:

 - https://github.com/ember-a11y/ember-a11y-testing/blob/master/vendor/shims/axe-core.js 
 - broccoli-funnel in package.json
 - broccoli-merge-trees in package.json

**Comment by MelSumner** [comment]
> This looks good to me. But there are some things left behind that are no longer used after this PR:
> 
> * https://github.com/ember-a11y/ember-a11y-testing/blob/master/vendor/shims/axe-core.js
> * broccoli-funnel in package.json
> * broccoli-merge-trees in package.json

ahh good catch, I'll fix that. Thank you, @ef4 !

**Comment by scalvert** [comment]
The beta and canary CI tests are failing in this PR. It looks like they're also failing in master, so we'll need to figure it out.

**Comment by drewlee** [comment]
Have we ran these with a bunch of host apps just to be sure this works as expected? My main concerns are
  1. Axe-core isn't inadvertently being included in non-test builds,
  2. The following build errors need to be removed which seems to come from Webpack or some other entity in ember-auto-import: ```
 WARNING in ./node_modules/axe-core/axe.js 11:149698-149705
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ /private/var/folders/c5/w1hrxnv55sx_303npp2r5q_h000510/T/broccoli-29237IvTtzxKWMRSR/cache-2222-bundler/staging/tests.js
 @ multi /private/var/folders/c5/w1hrxnv55sx_303npp2r5q_h000510/T/broccoli-29237IvTtzxKWMRSR/cache-2222-bundler/staging/l.js /private/var/folders/c5/w1hrxnv55sx_303npp2r5q_h000510/T/broccoli-29237IvTtzxKWMRSR/cache-2222-bundler/staging/tests.js

WARNING in ./node_modules/axe-core/axe.js
Module not found: Error: Can't resolve 'crypto' in '/Users/andlee/workspace/lighthouse-web_trunk/node_modules/axe-core'
 @ ./node_modules/axe-core/axe.js
```

**Comment by MelSumner** [comment]
@drewlee 

1. I haven't tried this with any host apps yet, I expected the tests in the addons to provide appropriate coverage
2. I'll look into these build errors to see if I can track it down, but if @ef4 has more context in the immediate, please weigh in. 

Thanks for the feedback!

**Comment by ef4** [comment]
It looks like axe-core is trying to fix that warning upstream. It's harmless but annoying. You can avoid it like this:

```js
autoImport: {
  webpack: {
    module: {
      noParse: /\baxe\.js$/
    }
  }
}
```

**Comment by drewlee** [comment]
@MelSumner I ran this through a few apps and everything looks good, outside of some messaging related to axe-core being deoptimized due to being over 500k in size. I think the "crypto" issue got fixed in axe-core itself, so we may need to bump it, but I need to verify. Afterwards, I can merge this and publish a new release later today.

**Comment by drewlee** [comment]
Deque hasn't published a release with the fix yet, so we'll need to add Edward's suggestion above.

**Comment by drewlee** [comment]
The "crypto" issue has been documented under https://github.com/dequelabs/axe-core/issues/2873, which I believe should be appropriately handled in axe-core itself.

**Review by drewlee — APPROVED** [review]
