### PR TITLE
Include axe-core in all non-prod environments

### LINKED ISSUE #61: "ReferenceError: axe is not defined" when upgrading to 0.2.0
# Summary
When upgrading an app from ember-a11y-testing 0.1.6 to 0.2.0, I get a JS console error `ReferenceError: axe is not defined` when running `ember server`.

When I run unit tests (`ember test --server`), I do not get these errors and unit tests behave as expected. App uses Ember 2.8 (the newest LTS).

# Steps to reproduce / test case
See pull request demonstrating changes:
https://github.com/abought/demo-ember-osf/pull/6

# Attempted fixes
Also attempted to make package.json and bower.json changes to bring project in line with changes made here.
https://github.com/ember-a11y/ember-a11y-testing/pull/58

Got the same result both before and after `08238ff`.

Reran blueprint and tried with a fresh install of node_modules and bower_components.  

Tried in Chrome 56 and FF 51, Mac OS.

### PR DESCRIPTION
**Pull request by trentmwillis**
Fixes #61. Verified by linking locally against the reproduction repo.

This was introduced when moving `axe-core` to `npm` (#58).

cc @abought

### CODE REVIEW

**Comment by abought** [comment]
Thanks! 

I've confirmed this works for me in development, in that I no longer receive console errors about a missing module. (and that it warns me about accessibility violations in development mode)

**Comment by trentmwillis** [comment]
Great! I'll be releasing a new version with this fix after fixing #60.

File: index.js [hunk 1]
```diff
@@ -24,7 +24,9 @@ module.exports = {
   included: function(app) {
     this._super.included(app);
 
-    app.import('vendor/axe-core/axe.js', { type: 'test' });
+    if (app.env !== 'production') {
```
Comment (rwjblue) [inline index.js]: Should be if `app.tests` (which handles the `ember test --environment=production` case also)
